package net.tecgurus.minipos.model;
// Generated Oct 5, 2020, 8:15:58 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "categoria", catalog = "miappio_cursopos")
public class Categoria implements java.io.Serializable {

	private Integer idcategoria;
	private String nombre;
	private String descripcion;
	

	public Categoria() {
	}

	public Categoria(String nombre) {
		this.nombre = nombre;
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcategoria", unique = true, nullable = false)
	public Integer getIdcategoria() {
		return this.idcategoria;
	}

	public void setIdcategoria(Integer idcategoria) {
		this.idcategoria = idcategoria;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}



}
