package net.tecgurus.minipos.model;
// Generated Oct 5, 2020, 8:15:58 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compra generated by hbm2java
 */
@Entity
@Table(name = "compra", catalog = "miappio_cursopos")
public class Compra implements java.io.Serializable {

	private Integer idcompra;
	private Cliente cliente;
	private Usuario usuario;
	private BigDecimal total;
	private Date fecha;
	private Set<Compraproducto> compraproductos = new HashSet<Compraproducto>(0);

	public Compra() {
		this.fecha = new Date();
	}

	public Compra(Cliente cliente, Usuario usuario, BigDecimal total, Date fecha) {
		this.cliente = cliente;
		this.usuario = usuario;
		this.total = total;
		this.fecha = fecha;
	}

	public Compra(Cliente cliente, Usuario usuario, BigDecimal total, Date fecha, Set<Compraproducto> compraproductos) {
		this.cliente = cliente;
		this.usuario = usuario;
		this.total = total;
		this.fecha = fecha;
		this.compraproductos = compraproductos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcompra", unique = true, nullable = false)
	public Integer getIdcompra() {
		return this.idcompra;
	}

	public void setIdcompra(Integer idcompra) {
		this.idcompra = idcompra;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idcliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "total", nullable = false, precision = 7)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "compra")
	public Set<Compraproducto> getCompraproductos() {
		return this.compraproductos;
	}

	public void setCompraproductos(Set<Compraproducto> compraproductos) {
		this.compraproductos = compraproductos;
	}

}
