package net.tecgurus.minipos.model;
// Generated Oct 5, 2020, 8:15:58 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Compuesta generated by hbm2java
 */
@Entity
@Table(name = "compuesta", catalog = "miappio_cursopos")
public class Compuesta implements java.io.Serializable {

	private CompuestaId id;
	private String descripcion;

	public Compuesta() {
	}

	public Compuesta(CompuestaId id, String descripcion) {
		this.id = id;
		this.descripcion = descripcion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idcompuesta", column = @Column(name = "idcompuesta", nullable = false)),
			@AttributeOverride(name = "idcompuestados", column = @Column(name = "idcompuestados", nullable = false)) })
	public CompuestaId getId() {
		return this.id;
	}

	public void setId(CompuestaId id) {
		this.id = id;
	}

	@Column(name = "descripcion", nullable = false, length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
