package net.tecgurus.minipos.model;
// Generated Oct 5, 2020, 8:15:58 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Compraproducto generated by hbm2java
 */
@Entity
@Table(name = "compraproducto", catalog = "miappio_cursopos")
public class Compraproducto implements java.io.Serializable {

	private Integer idcompraproducto;
	private Compra compra;
	private Producto producto;
	private int cantidad;
	private BigDecimal costo;

	public Compraproducto() {
	}

	public Compraproducto(Compra compra, Producto producto, int cantidad, BigDecimal costo) {
		this.compra = compra;
		this.producto = producto;
		this.cantidad = cantidad;
		this.costo = costo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcompraproducto", unique = true, nullable = false)
	public Integer getIdcompraproducto() {
		return this.idcompraproducto;
	}

	public void setIdcompraproducto(Integer idcompraproducto) {
		this.idcompraproducto = idcompraproducto;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idcompra", nullable = false)
	public Compra getCompra() {
		return this.compra;
	}

	public void setCompra(Compra compra) {
		this.compra = compra;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "costo", nullable = false, precision = 7)
	public BigDecimal getCosto() {
		return this.costo;
	}

	public void setCosto(BigDecimal costo) {
		this.costo = costo;
	}

}
